server:
  port: 8082
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://113.45.179.101:3306/hayishu_club?useSSL=false&characterEncoding=utf8
    username: root
    password: wzh121212
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8080
        username: nacos
        password: nacos
  application:
    name: clubservice
mybatis:
  type-aliases-package: org.example.club.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
---
server:
  port: 8082
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://113.45.179.101:3306/hayishu_club?useSSL=false
    username: root
    password: wzh121212
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8080
        username: nacos
        password: nacos
  application:
    name: clubservice
mybatis:
  type-aliases-package: org.example.club.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
---
spring:
  profiles:
    active: dev
