server:
  port: 8086
spring:
  profiles: dev
  application:
    name: orderservice
  datasource:
    url: jdbc:mysql://113.45.179.101:3306/hayishu_order?useSSL=false&characterEncoding=utf8
    username: root
    password: wzh121212
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
---
server:
  port: 8086
spring:
  profiles: pro
  application:
    name: orderservice
  datasource:
    url: jdbc:mysql://113.45.179.101:3306/hayishu_order?useSSL=false
    username: root
    password: wzh121212
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
        port: 8086
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
---
spring:
  profiles:
    active: dev
