server:
  port: 8085
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://113.45.179.101:3306/hayishu_cart?useSSL=false&characterEncoding=utf8
    username: root
    password: wzh121212
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 47.93.245.14:8848
  application:
    name: cartservice
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
---
server:
  port: 8085
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://113.45.179.101:3306/hayishu_cart?useSSL=false
    username: root
    password: wzh121212
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8080
  application:
    name: cartservice
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
---
spring:
  profiles:
    active: dev
